services:

  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./Dockerfile_web
    restart: always
    volumes:
      - static_value:/app/tgbot/static/
    env_file:
      - ./.env
    depends_on:
      - db

  tgbot:
    container_name: tgbot
    build:
      context: ./
      dockerfile: ./Dockerfile_bot
    restart: always
    volumes:
      - static_value:/app/tgbot/static/
    env_file:
      - ./.env
    depends_on:
      - web


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
    depends_on:
      - web

  redis:
    restart: always
    image: redis

  worker:
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile_celery
    volumes:
      - static_value:/app/tgbot/static/
    depends_on:
      - redis
      - web

volumes:
  static_value:
  db_value:
