services:

  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    container_name: web
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
    - "8000:8000"
    volumes:
      - static_value:/app/
    env_file:
      - ./.env
    depends_on:
      - db

  # bot:
  #   container_name: tgbot
  #   image: tgbot
  #   restart: always
  #   depends_on:
  #     - web
  #   command: python manage.py bot

#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../docs/:/usr/share/nginx/html/api/docs/
#    depends_on:
#      - tgbot

volumes:
  static_value:
  db_value:
