version: '3.8'
services:

#  db:
#    image: postgres:13.0-alpine
#    ports:
#      - 5432:5432
#    volumes:
#      - db_value:/var/lib/postgresql/data/
#    env_file:
#      - ./.env

  tgbot:
    build:
      context: ../tgbot
      dockerfile: Dockerfile
    restart: always
    ports:
     - "8000:8000"
    volumes:
      - static_value:/app/static/
    env_file:
      - ./.env

#  nginx:
#    image: nginx:1.19.3
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - ../docs/:/usr/share/nginx/html/api/docs/
#    depends_on:
#      - tgbot

volumes:
  static_value:
#  db_value: